Import all the required libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Read the data

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/ChaiCode Full Stack Data Science Cohort/Phase 1 - Statistics for Data Science/DescriptiveStats_18June_7PM/Population_Survey_Data.csv')
data.head()

   ID  Age Gender  Income  Education Region
0   1   62  Other   96138    Masters   East
1   2   65  Other   76543        PhD   East
2   3   71   Male  138887  Bachelors   East
3   4   18  Other  121643  Bachelors  South
4   5   21   Male  143192    Masters   East

In [ ]:
data.shape

(1000, 6)

1. Simple Random Sampling: 100 records randomly

In [ ]:
sample_data = data.sample(n = 100, random_state=44)
sample_data

      ID  Age  Gender  Income    Education Region
118  119   31    Male   71544      Masters   West
19    20   19  Female   67628    Bachelors  North
41    42   42    Male  107471  High School   West
425  426   64    Male   55738          PhD  South
221  222   31    Male   78882    Bachelors   East
..   ...  ...     ...     ...          ...    ...
143  144   39    Male   69453  High School   West
840  841   72   Other  103702    Bachelors   West
763  764   68  Female  106461      Masters  South
526  527   24  Female   24440    Bachelors   East
316  317   44  Female  132092    Bachelors   East

[100 rows x 6 columns]

2. Stratified Random Sampling

In [ ]:
stratified_sample_data = data.groupby('Region').apply(lambda x : x.sample(min(len(x),25), random_state=44))
stratified_sample_data.to_csv('stratified_sample_data.csv')

<ipython-input-7-f3aefa6aa341>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_sample_data = data.groupby('Region').apply(lambda x : x.sample(min(len(x),25), random_state=44))

Cluster Sampling: Manufacturing Data by Batch Number

In [ ]:
manufacturing_data = pd.read_csv('/content/drive/MyDrive/ChaiCode Full Stack Data Science Cohort/Phase 1 - Statistics for Data Science/DescriptiveStats_18June_7PM/Manufacturing_Data.csv')
manufacturing_data.head()

   ProductID  BatchNumber ProductionDate  Defective      Weight     Length
0          1           25     2024-01-09          0  462.453744  17.613212
1          2           45     2024-04-18          0  521.766704  15.899234
2          3           20     2024-04-11          0  498.369030  14.177899
3          4           31     2024-06-27          0  488.938762  16.498599
4          5           14     2023-10-27          0  524.459295  15.422276

In [ ]:
clusters = manufacturing_data['BatchNumber'].unique()
clusters

array([25, 45, 20, 31, 14,  8, 36, 30, 21,  9, 11, 42, 35, 47, 12, 22,  5,
       48, 23,  7, 44, 33, 38,  4, 18,  6, 28,  2, 34, 41, 40, 19, 16, 46,
       49, 43, 17,  3, 13, 10, 29, 32, 24, 26, 39, 15,  1, 27, 37])

In [ ]:
selected_clusters = np.random.choice(clusters, size = 5, replace = False)
selected_clusters

array([26, 27, 40, 19, 18])

In [ ]:
clustered_sample = manufacturing_data[manufacturing_data['BatchNumber'].isin(selected_clusters)]
print(clustered_sample)

     ProductID  BatchNumber ProductionDate  Defective      Weight     Length
38          39           18     2023-08-30          0  500.563397  16.537935
46          47           40     2023-12-13          0  522.484435  16.400715
50          51           19     2023-09-23          0  468.282948  10.339065
92          93           40     2024-03-01          0  478.880813  13.549656
96          97           18     2024-02-01          0  522.928640  15.310700
..         ...          ...            ...        ...         ...        ...
971        972           18     2024-01-27          0  489.091128  11.069078
972        973           40     2024-07-02          0  531.065653  14.211555
975        976           27     2024-04-13          0  496.300972  15.228057
980        981           40     2024-03-18          0  493.152639  16.151341
991        992           27     2024-05-21          0  501.317024  17.930302

[89 rows x 6 columns]

Systematic Sampling

In [ ]:
systematic_sample = data.iloc[::10, :]
systematic_sample

      ID  Age  Gender  Income    Education Region
0      1   62   Other   96138      Masters   East
10    11   39    Male   25241      Masters   West
20    21   56   Other  121272          PhD  South
30    31   27  Female   58115  High School   East
40    41   53  Female  147482    Bachelors  North
..   ...  ...     ...     ...          ...    ...
950  951   78    Male  121159          PhD  North
960  961   55  Female   34823    Bachelors  South
970  971   36   Other  108570    Bachelors  South
980  981   77  Female  123554    Bachelors  North
990  991   28  Female  139725      Masters  North

[100 rows x 6 columns]

Measures of Central Tendency: Mean, Median, Mode

In [ ]:
data.head()

   ID  Age Gender  Income  Education Region
0   1   62  Other   96138    Masters   East
1   2   65  Other   76543        PhD   East
2   3   71   Male  138887  Bachelors   East
3   4   18  Other  121643  Bachelors  South
4   5   21   Male  143192    Masters   East

Evaluate the measure of central tendency for the whole data followed by the simple random sample, stratified random sample, cluster sample and systematic sample.

Compare the means of all the different types of sample.

Finally, conclude which specific sampling technique mean value is almost similar to the population mean value.

In [ ]:
## Explore the measures of dispersion at your end: Range, IQR, Standard Deviation, Variance